---
# Install build tools and user

- name: install core development tools
  yum: name=$item state=latest
  with_items:
    $devpackages

- name: create $devuser user account
  user: name=$devuser generate_ssh_key=yes

- name: inject pubkey for user
  authorized_key: user=$devuser key="${mypubkey}"

- name: copy RPM signing key
  copy: src=RPM-GPG-KEY-${repo.name} dest=/home/$devuser owner=$devuser group=$devuser

- name: import RPM signing key
  command: /bin/su -c "/usr/bin/gpg --import /home/$devuser/RPM-GPG-KEY-${repo.name}" $devuser

- name: create RPM directory structure
  command: /bin/su -c "/bin/mkdir -p /home/$devuser/rpmbuild/${item}" $devuser
  with_items:
  - BUILD
  - RPMS
  - SOURCES
  - SPECS
  - SRPMS

- name: seed .rpmmacros
  template: src=rpmmacros dest=/home/$devuser/.rpmmacros owner=$devuser group=$devuser

