---
# TODO: drive more configuration with variables

- hosts: centos6build
  user: root
  vars:
    smtp_gateway: localhost
  roles:
  - role: epel
  - role: puias
  - role: python27
  - role: centos6-common
  - role: centos6-devtools
  - role: justhub
  - role: nginx
  - role: jenkins
