---
# setup a user to build RPMs

- name: Create rpmdev user account
  user: name=rpmdev generate_ssh_key=yes

- name: Inject pubkey for user
  authorized_key: user=rpmdev key="${mypubkey}"

- name: Copy RPM signing key
  copy: src=RPM-GPG-KEY-psftw dest=/home/rpmdev owner=rpmdev group=rpmdev

- name: Import RPM signing key
  command: /bin/su -c "/usr/bin/gpg --import /home/rpmdev/RPM-GPG-KEY-psftw" rpmdev

- name: Create RPM directory structure
  command: /bin/su -c "/bin/mkdir -p /home/rpmdev/rpmbuild/${subdir}" rpmdev
  with_items:
  - BUILD
  - RPMS
  - SOURCES
  - SPECS
  - SRPMS

- name: Seed .rpmmacros
  copy: src=rpmmacros dest=/home/rpmdev/.rpmmacros
