---

devpackages:
- autoconf
- automake
- binutils
- bison
- byacc
- cscope
- ctags
- cvs
- diffstat
- doxygen
- elfutils
- flex
- gcc
- gcc-c++
- gcc-gfortran
- gettext
- git
- indent
- intltool
- libtool
- make
- patch
- patchutils
- pkgconfig
- rcs
- redhat-rpm-config
- rpm-build
- rpmdevtools
- rpmlint
- subversion
- swig
- systemtap

