---

- name: add EPEL repository
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: add EPEL GPG KEY
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: yum update -y
  command: /usr/bin/yum update -y

- name: install some essential tools
  yum: name={{ item }} state=latest
  with_items:
  - vim
  - screen
  - dstat
  - man

