---
# install/upgrade essential tools

- name: disable iptables
  service: name=iptables state=stopped enabled=no

- name: disable ip6tables
  service: name=ip6tables state=stopped enabled=no

- name: install essential tools
  yum: name={{ item }} state=present
  with_items:
  - vim
  - screen
  - man
  - zip
  - unzip
